# all three csv files generated by python simulation files

all_matches<-read.csv("all_matches.csv", sep=";")
groups<-read.csv("groups.csv", sep=";")
champs<-read.csv("champs.csv", sep=";")

library(dplyr)
library(data.table)
library(tidyr)

all_matches %>% 
  summarise(suma=sum(goals1)+sum(goals2))/64000000

poland<-all_matches %>% 
  filter(team1=='Poland' | team2=='Poland')

#wholl be champion
df_champs<-as.data.frame(champs %>% 
  group_by(champ) %>% 
  summarise(wins=n()) %>% 
  mutate(winratio=wins/1000000, wins=NULL) %>% 
  arrange(-winratio))

df_champs #TODO
write.csv(df_champs,"df_champs.csv", row.names = FALSE)


#wholl adavance to knockouts
awanse<-c(groups$X1st,groups$X2nd)
awanse<-as.data.frame(awanse)
as.data.frame(awanse %>% 
  group_by(awanse) %>% 
  summarise(adv=n()) %>% 
  mutate(adv_ratio=adv/1000000) %>% 
  arrange(-adv_ratio))


as.data.frame(all_matches %>% 
  mutate(result=case_when(
    goals1>goals2~'Host',
    goals1<goals2~'Away',
    TRUE~'Draw'
  )) %>% 
  group_by(result) %>% 
  summarise(res_ratio=n()/64000000))

#poland matches
poland %>% 
  filter(idx==14) %>% 
  mutate(result=case_when(
    goals1>goals2~'Mexico',
    goals1<goals2~'Poland',
    TRUE~'Draw'
  )) %>% 
  group_by(result) %>% 
  summarise(res_ratio=n()/1000000)

poland %>% 
  filter(idx==14) %>% 
  summarise(g1=mean(goals1), g2=mean(goals2))

poland %>% 
  filter(idx==16) %>% 
  mutate(result=case_when(
    goals2>goals1~'Saudi_Arabia',
    goals2<goals1~'Poland',
    TRUE~'Draw'
  )) %>% 
  group_by(result) %>% 
  summarise(res_ratio=n()/1000000)

poland %>% 
  filter(idx==16) %>% 
  summarise(g1=mean(goals1), g2=mean(goals2))

poland %>% 
  filter(idx==17) %>% 
  mutate(result=case_when(
    goals2>goals1~'Argentina',
    goals2<goals1~'Poland',
    TRUE~'Draw'
  )) %>% 
  group_by(result) %>% 
  summarise(res_ratio=n()/1000000)

poland %>% 
  filter(idx==17) %>% 
  summarise(g1=mean(goals1), g2=mean(goals2))

#poland position in group
as.data.frame(groups %>% 
  filter(group_name=='C') %>% 
  mutate(polando=case_when(
    X1st=='Poland'~1,
    X2nd=='Poland'~2,
    X3rd=='Poland'~3,
    TRUE~4,
  )) %>% 
  group_by(polando) %>% 
  summarise(pos_rate=n()/1000000))

#rivals of poland
as.data.frame(all_matches %>% 
  filter(idx>48 & (team1=='Poland' | team2=='Poland')) %>% 
  mutate(phase=case_when(
    idx<57~'rof16',
    idx<61~'qf',
    idx<63~'sf',
    idx==63~'mo3rd',
    TRUE~'final'
  )) %>% 
  filter(phase=='rof16') %>% 
  mutate(rival=case_when(
    team1=='Poland'~team2,
    TRUE~team1
  )) %>% 
  mutate(did_we_won=case_when(
      team1=='Poland'&(goals1>goals2 | pen1>pen2)~1,
      team2=='Poland'&(goals2>goals1 | pen2>pen1)~1,
      T~0)) %>% 
  group_by(rival) %>% 
  summarise(nriv=n(), winratio=mean(did_we_won)) %>% 
  mutate(ratio_riv=nriv/sum(nriv), nriv=NULL) %>% 
  arrange(-ratio_riv))

as.data.frame(poland %>% 
  filter(idx>48) %>% 
  mutate(rival=case_when(
    team1=='Poland'~team2,
    TRUE~team1
  )) %>% 
  mutate(did_we_won=case_when(
    team1=='Poland'&(goals1>goals2 | pen1>pen2)~1,
    team2=='Poland'&(goals2>goals1 | pen2>pen1)~1,
    T~0)) %>% 
  group_by(rival) %>% 
  summarise(nriv=n(), winratio=mean(did_we_won)) %>% 
  arrange(-nriv))



#only final match
final<-as.data.frame(all_matches %>% 
  filter(idx==64) %>% 
  mutate(nteam1=ifelse(team1<team2,team1,team2), nteam2=ifelse(team1<team2,team2,team1),
         ngoals1=ifelse(team1<team2,goals1,goals2), ngoals2=ifelse(team1<team2,goals2,goals1),
         npen1=ifelse(team1<team2,pen1,pen2), npen2=ifelse(team1<team2,pen2,pen1),
         team1=NULL, team2=NULL, goals1=NULL, goals2=NULL, pen1=NULL, pen2=NULL,
         doesteam1won=case_when(
           (ngoals1>ngoals2)|(npen1>npen2)~1,
           T~0
         )))

#most common final match
as.data.frame(final %>% 
  group_by(nteam1, nteam2) %>% 
  summarise(ratfinals=n()/1000000,
            avggoals1=mean(ngoals1), avggoals2=mean(ngoals2),
            team1winratio=mean(doesteam1won)) %>% 
  arrange(-ratfinals))[486,] #%>% 
  #filter(nteam1=='Cameroon', nteam2=='Morocco')

#specific finals data
final %>% 
  filter(nteam1=='Argentina', nteam2=='Portugal') %>% 
  mutate(winner=case_when(
    (ngoals1>ngoals2)|(npen1>npen2)~'team1',
    T~'team2'
  )) %>% 
  group_by(winner) %>% 
  summarise(wins=n())

final %>% 
  filter(nteam1=='Cameroon', nteam2=='Morocco') %>% 
  mutate(winner=case_when(
    (ngoals1>ngoals2)|(npen1>npen2)~'team1',
    T~'team2'
  )) %>% 
  group_by(winner) %>% 
  summarise(wins=n())

all_matches %>% 
  filter(idx==63) %>% 
  mutate(winner=case_when(
    goals1>goals2~team1,
    goals2>goals1~team2,
    pen1>pen2~team1,
    pen2>pen1~team2)) %>% 
  group_by(winner) %>% 
  summarise(ratio_3rd=n()/1000000) %>% 
  arrange(-ratio_3rd)

all_matches %>% 
  filter((team1=='Argentina' & team2=='Portugal') | (team2=='Argentina' & team1=='Portugal')) %>% 
  group_by(idx) %>% 
  summarise(n()) %>% 
  summarise(sum())

# poland's performance in knockouts
poland %>% 
  mutate(phase=case_when(
    idx<48~'group',
    idx<57~'rof16',
    idx<61~'qf',
    idx<63~'sf',
    idx==63~'mo3rd',
    TRUE~'final'
  )) %>% 
  group_by(phase) %>% 
  summarise(rat_phases=n()/1000000)

# poland's performance in finals
poland %>% 
  filter(idx==64 | idx==63) %>% 
  mutate(winner=case_when(
    team1=='Poland'&(goals1>goals2 | pen1>pen2)~'Poland',
    team2=='Poland'&(goals2>goals1 | pen2>pen1)~'Poland',
    T~'rival')) %>% 
  mutate(place=case_when(
    (idx==63)&(winner=='rival')~'4th',
    (idx==63)&(winner=='Poland')~'3rd',
    (idx==64)&(winner=='rival')~'2nd',
    T~'1st')) %>% 
  group_by(place) %>% 
  summarise(rat_place=n()/1000000)

#common semifinals
all_matches %>% 
  filter(idx==62 | idx==61) %>% 
  mutate(nteam1=ifelse(team1<team2,team1,team2), nteam2=ifelse(team1<team2,team2,team1)) %>%
  group_by(nteam1, nteam2) %>% 
  summarise(rat=n()/2000000) %>% 
  arrange(-rat)

#polish goals in whole tournament
poland %>% 
  filter(idx<48) %>% 
  mutate(polgoals=ifelse(team1=='Poland',goals1,goals2),
         vspolgoals=ifelse(team1=='Poland',goals2,goals1)) %>% 
  summarise(avgscored=sum(polgoals)/1000000, avgconceded=sum(vspolgoals)/1000000)


with_phase<-all_matches %>% 
  mutate(phase=case_when(
    idx<=48~'group',
    idx<57~'rof16',
    idx<61~'qf',
    idx<63~'sf',
    idx==63~'mo3rd',
    TRUE~'final'
  ))
df1<-with_phase %>% 
  select(team1, phase)
df2<-with_phase %>% 
  select(team2, phase) %>% 
  mutate(team1=team2, team2=NULL)
phaeses<-rbind(df1, df2)
as.data.frame(phaeses %>% 
  group_by(team1, phase) %>% 
  summarise(n=n()/1000000) %>% 
  pivot_wider(names_from = phase, values_from = n) %>% 
  relocate(c('team1', 'group', 'rof16', 'qf', 'sf', 'final')))
